gdjs.warningCode = {};
gdjs.warningCode.localVariables = [];
gdjs.warningCode.idToCallbackMap = new Map();
gdjs.warningCode.GDwarningScreenObjects1= [];
gdjs.warningCode.GDwarningScreenObjects2= [];
gdjs.warningCode.GDNewTextObjects1= [];
gdjs.warningCode.GDNewTextObjects2= [];
gdjs.warningCode.GDBlock1Objects1= [];
gdjs.warningCode.GDBlock1Objects2= [];
gdjs.warningCode.GDWoodObjects1= [];
gdjs.warningCode.GDWoodObjects2= [];
gdjs.warningCode.GDGrassGroundObjects1= [];
gdjs.warningCode.GDGrassGroundObjects2= [];
gdjs.warningCode.GDBlockInvObjects1= [];
gdjs.warningCode.GDBlockInvObjects2= [];
gdjs.warningCode.GDStairs1Objects1= [];
gdjs.warningCode.GDStairs1Objects2= [];
gdjs.warningCode.GDStairsInvObjects1= [];
gdjs.warningCode.GDStairsInvObjects2= [];
gdjs.warningCode.GDWoodStrsObjects1= [];
gdjs.warningCode.GDWoodStrsObjects2= [];
gdjs.warningCode.GDStopCrouchTrgObjects1= [];
gdjs.warningCode.GDStopCrouchTrgObjects2= [];
gdjs.warningCode.GDCameraObjects1= [];
gdjs.warningCode.GDCameraObjects2= [];
gdjs.warningCode.GDCamera2Objects1= [];
gdjs.warningCode.GDCamera2Objects2= [];
gdjs.warningCode.GDCameraColliderObjects1= [];
gdjs.warningCode.GDCameraColliderObjects2= [];
gdjs.warningCode.GDPaperObjects1= [];
gdjs.warningCode.GDPaperObjects2= [];
gdjs.warningCode.GDKeyObjects1= [];
gdjs.warningCode.GDKeyObjects2= [];
gdjs.warningCode.GDItemObjects1= [];
gdjs.warningCode.GDItemObjects2= [];
gdjs.warningCode.GDVendingMachine1Objects1= [];
gdjs.warningCode.GDVendingMachine1Objects2= [];
gdjs.warningCode.GDVendingMachine2Objects1= [];
gdjs.warningCode.GDVendingMachine2Objects2= [];
gdjs.warningCode.GDInteractTextObjects1= [];
gdjs.warningCode.GDInteractTextObjects2= [];
gdjs.warningCode.GDPaperUIObjects1= [];
gdjs.warningCode.GDPaperUIObjects2= [];
gdjs.warningCode.GDPaperTextObjects1= [];
gdjs.warningCode.GDPaperTextObjects2= [];
gdjs.warningCode.GDDoorObjects1= [];
gdjs.warningCode.GDDoorObjects2= [];
gdjs.warningCode.GDDoorWayPointObjects1= [];
gdjs.warningCode.GDDoorWayPointObjects2= [];
gdjs.warningCode.GDFadeBLACKObjects1= [];
gdjs.warningCode.GDFadeBLACKObjects2= [];
gdjs.warningCode.GDCrossObjects1= [];
gdjs.warningCode.GDCrossObjects2= [];
gdjs.warningCode.GDInfo_9595TextObjects1= [];
gdjs.warningCode.GDInfo_9595TextObjects2= [];
gdjs.warningCode.GDScary_9595PersonObjects1= [];
gdjs.warningCode.GDScary_9595PersonObjects2= [];
gdjs.warningCode.GDItemsUIObjects1= [];
gdjs.warningCode.GDItemsUIObjects2= [];
gdjs.warningCode.GDStaminaObjects1= [];
gdjs.warningCode.GDStaminaObjects2= [];
gdjs.warningCode.GDBaldiUIObjects1= [];
gdjs.warningCode.GDBaldiUIObjects2= [];
gdjs.warningCode.GDBaldiUIStaminaObjects1= [];
gdjs.warningCode.GDBaldiUIStaminaObjects2= [];
gdjs.warningCode.GDItemSlotObjects1= [];
gdjs.warningCode.GDItemSlotObjects2= [];
gdjs.warningCode.GDItemInventoryObjects1= [];
gdjs.warningCode.GDItemInventoryObjects2= [];
gdjs.warningCode.GDSodaSplashObjects1= [];
gdjs.warningCode.GDSodaSplashObjects2= [];
gdjs.warningCode.GDBearTrapObjects1= [];
gdjs.warningCode.GDBearTrapObjects2= [];
gdjs.warningCode.GDBlackBarsObjects1= [];
gdjs.warningCode.GDBlackBarsObjects2= [];
gdjs.warningCode.GDVendingMachine3Objects1= [];
gdjs.warningCode.GDVendingMachine3Objects2= [];
gdjs.warningCode.GDBaldiEnemyObjects1= [];
gdjs.warningCode.GDBaldiEnemyObjects2= [];
gdjs.warningCode.GDfloorObjects1= [];
gdjs.warningCode.GDfloorObjects2= [];
gdjs.warningCode.GDfloor2Objects1= [];
gdjs.warningCode.GDfloor2Objects2= [];
gdjs.warningCode.GDBlock2Objects1= [];
gdjs.warningCode.GDBlock2Objects2= [];
gdjs.warningCode.GDBlock3Objects1= [];
gdjs.warningCode.GDBlock3Objects2= [];
gdjs.warningCode.GDfakewallObjects1= [];
gdjs.warningCode.GDfakewallObjects2= [];
gdjs.warningCode.GDBlock3AltObjects1= [];
gdjs.warningCode.GDBlock3AltObjects2= [];
gdjs.warningCode.GDelevatorfloorObjects1= [];
gdjs.warningCode.GDelevatorfloorObjects2= [];
gdjs.warningCode.GDElevatorWallObjects1= [];
gdjs.warningCode.GDElevatorWallObjects2= [];
gdjs.warningCode.GDRedNetObjects1= [];
gdjs.warningCode.GDRedNetObjects2= [];
gdjs.warningCode.GDGreenNetObjects1= [];
gdjs.warningCode.GDGreenNetObjects2= [];
gdjs.warningCode.GDYellowNetObjects1= [];
gdjs.warningCode.GDYellowNetObjects2= [];
gdjs.warningCode.GDBlueNetObjects1= [];
gdjs.warningCode.GDBlueNetObjects2= [];
gdjs.warningCode.GDRedFloorObjects1= [];
gdjs.warningCode.GDRedFloorObjects2= [];
gdjs.warningCode.GDGreenFloorObjects1= [];
gdjs.warningCode.GDGreenFloorObjects2= [];
gdjs.warningCode.GDYellowFloorObjects1= [];
gdjs.warningCode.GDYellowFloorObjects2= [];
gdjs.warningCode.GDBlueFloorObjects1= [];
gdjs.warningCode.GDBlueFloorObjects2= [];
gdjs.warningCode.GDBallpitBallsObjects1= [];
gdjs.warningCode.GDBallpitBallsObjects2= [];
gdjs.warningCode.GDHandObjects1= [];
gdjs.warningCode.GDHandObjects2= [];
gdjs.warningCode.GDhandmarkerObjects1= [];
gdjs.warningCode.GDhandmarkerObjects2= [];
gdjs.warningCode.GDhandmarker2Objects1= [];
gdjs.warningCode.GDhandmarker2Objects2= [];
gdjs.warningCode.GDcursorObjects1= [];
gdjs.warningCode.GDcursorObjects2= [];
gdjs.warningCode.GDPaddedWallObjects1= [];
gdjs.warningCode.GDPaddedWallObjects2= [];
gdjs.warningCode.GDPaddedFloorObjects1= [];
gdjs.warningCode.GDPaddedFloorObjects2= [];
gdjs.warningCode.GDPaddedWallSMG4Objects1= [];
gdjs.warningCode.GDPaddedWallSMG4Objects2= [];
gdjs.warningCode.GDBlock4Objects1= [];
gdjs.warningCode.GDBlock4Objects2= [];
gdjs.warningCode.GDBlock1DetentionObjects1= [];
gdjs.warningCode.GDBlock1DetentionObjects2= [];
gdjs.warningCode.GDPosterObjects1= [];
gdjs.warningCode.GDPosterObjects2= [];
gdjs.warningCode.GDPoster2Objects1= [];
gdjs.warningCode.GDPoster2Objects2= [];
gdjs.warningCode.GDPoster3Objects1= [];
gdjs.warningCode.GDPoster3Objects2= [];


gdjs.warningCode.eventsList0 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
{
{gdjs.evtTools.window.setFullScreen(runtimeScene, true, true);
}
}

}


{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.isMouseButtonReleased(runtimeScene, "Left");
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "titleNew", false);
}
}

}


{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.runtimeScene.sceneJustBegins(runtimeScene);
if (isConditionTrue_0) {
{gdjs.evtTools.sound.playMusic(runtimeScene, "Warning.wav", true, 100, 1);
}
}

}


};

gdjs.warningCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.warningCode.GDwarningScreenObjects1.length = 0;
gdjs.warningCode.GDwarningScreenObjects2.length = 0;
gdjs.warningCode.GDNewTextObjects1.length = 0;
gdjs.warningCode.GDNewTextObjects2.length = 0;
gdjs.warningCode.GDBlock1Objects1.length = 0;
gdjs.warningCode.GDBlock1Objects2.length = 0;
gdjs.warningCode.GDWoodObjects1.length = 0;
gdjs.warningCode.GDWoodObjects2.length = 0;
gdjs.warningCode.GDGrassGroundObjects1.length = 0;
gdjs.warningCode.GDGrassGroundObjects2.length = 0;
gdjs.warningCode.GDBlockInvObjects1.length = 0;
gdjs.warningCode.GDBlockInvObjects2.length = 0;
gdjs.warningCode.GDStairs1Objects1.length = 0;
gdjs.warningCode.GDStairs1Objects2.length = 0;
gdjs.warningCode.GDStairsInvObjects1.length = 0;
gdjs.warningCode.GDStairsInvObjects2.length = 0;
gdjs.warningCode.GDWoodStrsObjects1.length = 0;
gdjs.warningCode.GDWoodStrsObjects2.length = 0;
gdjs.warningCode.GDStopCrouchTrgObjects1.length = 0;
gdjs.warningCode.GDStopCrouchTrgObjects2.length = 0;
gdjs.warningCode.GDCameraObjects1.length = 0;
gdjs.warningCode.GDCameraObjects2.length = 0;
gdjs.warningCode.GDCamera2Objects1.length = 0;
gdjs.warningCode.GDCamera2Objects2.length = 0;
gdjs.warningCode.GDCameraColliderObjects1.length = 0;
gdjs.warningCode.GDCameraColliderObjects2.length = 0;
gdjs.warningCode.GDPaperObjects1.length = 0;
gdjs.warningCode.GDPaperObjects2.length = 0;
gdjs.warningCode.GDKeyObjects1.length = 0;
gdjs.warningCode.GDKeyObjects2.length = 0;
gdjs.warningCode.GDItemObjects1.length = 0;
gdjs.warningCode.GDItemObjects2.length = 0;
gdjs.warningCode.GDVendingMachine1Objects1.length = 0;
gdjs.warningCode.GDVendingMachine1Objects2.length = 0;
gdjs.warningCode.GDVendingMachine2Objects1.length = 0;
gdjs.warningCode.GDVendingMachine2Objects2.length = 0;
gdjs.warningCode.GDInteractTextObjects1.length = 0;
gdjs.warningCode.GDInteractTextObjects2.length = 0;
gdjs.warningCode.GDPaperUIObjects1.length = 0;
gdjs.warningCode.GDPaperUIObjects2.length = 0;
gdjs.warningCode.GDPaperTextObjects1.length = 0;
gdjs.warningCode.GDPaperTextObjects2.length = 0;
gdjs.warningCode.GDDoorObjects1.length = 0;
gdjs.warningCode.GDDoorObjects2.length = 0;
gdjs.warningCode.GDDoorWayPointObjects1.length = 0;
gdjs.warningCode.GDDoorWayPointObjects2.length = 0;
gdjs.warningCode.GDFadeBLACKObjects1.length = 0;
gdjs.warningCode.GDFadeBLACKObjects2.length = 0;
gdjs.warningCode.GDCrossObjects1.length = 0;
gdjs.warningCode.GDCrossObjects2.length = 0;
gdjs.warningCode.GDInfo_9595TextObjects1.length = 0;
gdjs.warningCode.GDInfo_9595TextObjects2.length = 0;
gdjs.warningCode.GDScary_9595PersonObjects1.length = 0;
gdjs.warningCode.GDScary_9595PersonObjects2.length = 0;
gdjs.warningCode.GDItemsUIObjects1.length = 0;
gdjs.warningCode.GDItemsUIObjects2.length = 0;
gdjs.warningCode.GDStaminaObjects1.length = 0;
gdjs.warningCode.GDStaminaObjects2.length = 0;
gdjs.warningCode.GDBaldiUIObjects1.length = 0;
gdjs.warningCode.GDBaldiUIObjects2.length = 0;
gdjs.warningCode.GDBaldiUIStaminaObjects1.length = 0;
gdjs.warningCode.GDBaldiUIStaminaObjects2.length = 0;
gdjs.warningCode.GDItemSlotObjects1.length = 0;
gdjs.warningCode.GDItemSlotObjects2.length = 0;
gdjs.warningCode.GDItemInventoryObjects1.length = 0;
gdjs.warningCode.GDItemInventoryObjects2.length = 0;
gdjs.warningCode.GDSodaSplashObjects1.length = 0;
gdjs.warningCode.GDSodaSplashObjects2.length = 0;
gdjs.warningCode.GDBearTrapObjects1.length = 0;
gdjs.warningCode.GDBearTrapObjects2.length = 0;
gdjs.warningCode.GDBlackBarsObjects1.length = 0;
gdjs.warningCode.GDBlackBarsObjects2.length = 0;
gdjs.warningCode.GDVendingMachine3Objects1.length = 0;
gdjs.warningCode.GDVendingMachine3Objects2.length = 0;
gdjs.warningCode.GDBaldiEnemyObjects1.length = 0;
gdjs.warningCode.GDBaldiEnemyObjects2.length = 0;
gdjs.warningCode.GDfloorObjects1.length = 0;
gdjs.warningCode.GDfloorObjects2.length = 0;
gdjs.warningCode.GDfloor2Objects1.length = 0;
gdjs.warningCode.GDfloor2Objects2.length = 0;
gdjs.warningCode.GDBlock2Objects1.length = 0;
gdjs.warningCode.GDBlock2Objects2.length = 0;
gdjs.warningCode.GDBlock3Objects1.length = 0;
gdjs.warningCode.GDBlock3Objects2.length = 0;
gdjs.warningCode.GDfakewallObjects1.length = 0;
gdjs.warningCode.GDfakewallObjects2.length = 0;
gdjs.warningCode.GDBlock3AltObjects1.length = 0;
gdjs.warningCode.GDBlock3AltObjects2.length = 0;
gdjs.warningCode.GDelevatorfloorObjects1.length = 0;
gdjs.warningCode.GDelevatorfloorObjects2.length = 0;
gdjs.warningCode.GDElevatorWallObjects1.length = 0;
gdjs.warningCode.GDElevatorWallObjects2.length = 0;
gdjs.warningCode.GDRedNetObjects1.length = 0;
gdjs.warningCode.GDRedNetObjects2.length = 0;
gdjs.warningCode.GDGreenNetObjects1.length = 0;
gdjs.warningCode.GDGreenNetObjects2.length = 0;
gdjs.warningCode.GDYellowNetObjects1.length = 0;
gdjs.warningCode.GDYellowNetObjects2.length = 0;
gdjs.warningCode.GDBlueNetObjects1.length = 0;
gdjs.warningCode.GDBlueNetObjects2.length = 0;
gdjs.warningCode.GDRedFloorObjects1.length = 0;
gdjs.warningCode.GDRedFloorObjects2.length = 0;
gdjs.warningCode.GDGreenFloorObjects1.length = 0;
gdjs.warningCode.GDGreenFloorObjects2.length = 0;
gdjs.warningCode.GDYellowFloorObjects1.length = 0;
gdjs.warningCode.GDYellowFloorObjects2.length = 0;
gdjs.warningCode.GDBlueFloorObjects1.length = 0;
gdjs.warningCode.GDBlueFloorObjects2.length = 0;
gdjs.warningCode.GDBallpitBallsObjects1.length = 0;
gdjs.warningCode.GDBallpitBallsObjects2.length = 0;
gdjs.warningCode.GDHandObjects1.length = 0;
gdjs.warningCode.GDHandObjects2.length = 0;
gdjs.warningCode.GDhandmarkerObjects1.length = 0;
gdjs.warningCode.GDhandmarkerObjects2.length = 0;
gdjs.warningCode.GDhandmarker2Objects1.length = 0;
gdjs.warningCode.GDhandmarker2Objects2.length = 0;
gdjs.warningCode.GDcursorObjects1.length = 0;
gdjs.warningCode.GDcursorObjects2.length = 0;
gdjs.warningCode.GDPaddedWallObjects1.length = 0;
gdjs.warningCode.GDPaddedWallObjects2.length = 0;
gdjs.warningCode.GDPaddedFloorObjects1.length = 0;
gdjs.warningCode.GDPaddedFloorObjects2.length = 0;
gdjs.warningCode.GDPaddedWallSMG4Objects1.length = 0;
gdjs.warningCode.GDPaddedWallSMG4Objects2.length = 0;
gdjs.warningCode.GDBlock4Objects1.length = 0;
gdjs.warningCode.GDBlock4Objects2.length = 0;
gdjs.warningCode.GDBlock1DetentionObjects1.length = 0;
gdjs.warningCode.GDBlock1DetentionObjects2.length = 0;
gdjs.warningCode.GDPosterObjects1.length = 0;
gdjs.warningCode.GDPosterObjects2.length = 0;
gdjs.warningCode.GDPoster2Objects1.length = 0;
gdjs.warningCode.GDPoster2Objects2.length = 0;
gdjs.warningCode.GDPoster3Objects1.length = 0;
gdjs.warningCode.GDPoster3Objects2.length = 0;

gdjs.warningCode.eventsList0(runtimeScene);
gdjs.warningCode.GDwarningScreenObjects1.length = 0;
gdjs.warningCode.GDwarningScreenObjects2.length = 0;
gdjs.warningCode.GDNewTextObjects1.length = 0;
gdjs.warningCode.GDNewTextObjects2.length = 0;
gdjs.warningCode.GDBlock1Objects1.length = 0;
gdjs.warningCode.GDBlock1Objects2.length = 0;
gdjs.warningCode.GDWoodObjects1.length = 0;
gdjs.warningCode.GDWoodObjects2.length = 0;
gdjs.warningCode.GDGrassGroundObjects1.length = 0;
gdjs.warningCode.GDGrassGroundObjects2.length = 0;
gdjs.warningCode.GDBlockInvObjects1.length = 0;
gdjs.warningCode.GDBlockInvObjects2.length = 0;
gdjs.warningCode.GDStairs1Objects1.length = 0;
gdjs.warningCode.GDStairs1Objects2.length = 0;
gdjs.warningCode.GDStairsInvObjects1.length = 0;
gdjs.warningCode.GDStairsInvObjects2.length = 0;
gdjs.warningCode.GDWoodStrsObjects1.length = 0;
gdjs.warningCode.GDWoodStrsObjects2.length = 0;
gdjs.warningCode.GDStopCrouchTrgObjects1.length = 0;
gdjs.warningCode.GDStopCrouchTrgObjects2.length = 0;
gdjs.warningCode.GDCameraObjects1.length = 0;
gdjs.warningCode.GDCameraObjects2.length = 0;
gdjs.warningCode.GDCamera2Objects1.length = 0;
gdjs.warningCode.GDCamera2Objects2.length = 0;
gdjs.warningCode.GDCameraColliderObjects1.length = 0;
gdjs.warningCode.GDCameraColliderObjects2.length = 0;
gdjs.warningCode.GDPaperObjects1.length = 0;
gdjs.warningCode.GDPaperObjects2.length = 0;
gdjs.warningCode.GDKeyObjects1.length = 0;
gdjs.warningCode.GDKeyObjects2.length = 0;
gdjs.warningCode.GDItemObjects1.length = 0;
gdjs.warningCode.GDItemObjects2.length = 0;
gdjs.warningCode.GDVendingMachine1Objects1.length = 0;
gdjs.warningCode.GDVendingMachine1Objects2.length = 0;
gdjs.warningCode.GDVendingMachine2Objects1.length = 0;
gdjs.warningCode.GDVendingMachine2Objects2.length = 0;
gdjs.warningCode.GDInteractTextObjects1.length = 0;
gdjs.warningCode.GDInteractTextObjects2.length = 0;
gdjs.warningCode.GDPaperUIObjects1.length = 0;
gdjs.warningCode.GDPaperUIObjects2.length = 0;
gdjs.warningCode.GDPaperTextObjects1.length = 0;
gdjs.warningCode.GDPaperTextObjects2.length = 0;
gdjs.warningCode.GDDoorObjects1.length = 0;
gdjs.warningCode.GDDoorObjects2.length = 0;
gdjs.warningCode.GDDoorWayPointObjects1.length = 0;
gdjs.warningCode.GDDoorWayPointObjects2.length = 0;
gdjs.warningCode.GDFadeBLACKObjects1.length = 0;
gdjs.warningCode.GDFadeBLACKObjects2.length = 0;
gdjs.warningCode.GDCrossObjects1.length = 0;
gdjs.warningCode.GDCrossObjects2.length = 0;
gdjs.warningCode.GDInfo_9595TextObjects1.length = 0;
gdjs.warningCode.GDInfo_9595TextObjects2.length = 0;
gdjs.warningCode.GDScary_9595PersonObjects1.length = 0;
gdjs.warningCode.GDScary_9595PersonObjects2.length = 0;
gdjs.warningCode.GDItemsUIObjects1.length = 0;
gdjs.warningCode.GDItemsUIObjects2.length = 0;
gdjs.warningCode.GDStaminaObjects1.length = 0;
gdjs.warningCode.GDStaminaObjects2.length = 0;
gdjs.warningCode.GDBaldiUIObjects1.length = 0;
gdjs.warningCode.GDBaldiUIObjects2.length = 0;
gdjs.warningCode.GDBaldiUIStaminaObjects1.length = 0;
gdjs.warningCode.GDBaldiUIStaminaObjects2.length = 0;
gdjs.warningCode.GDItemSlotObjects1.length = 0;
gdjs.warningCode.GDItemSlotObjects2.length = 0;
gdjs.warningCode.GDItemInventoryObjects1.length = 0;
gdjs.warningCode.GDItemInventoryObjects2.length = 0;
gdjs.warningCode.GDSodaSplashObjects1.length = 0;
gdjs.warningCode.GDSodaSplashObjects2.length = 0;
gdjs.warningCode.GDBearTrapObjects1.length = 0;
gdjs.warningCode.GDBearTrapObjects2.length = 0;
gdjs.warningCode.GDBlackBarsObjects1.length = 0;
gdjs.warningCode.GDBlackBarsObjects2.length = 0;
gdjs.warningCode.GDVendingMachine3Objects1.length = 0;
gdjs.warningCode.GDVendingMachine3Objects2.length = 0;
gdjs.warningCode.GDBaldiEnemyObjects1.length = 0;
gdjs.warningCode.GDBaldiEnemyObjects2.length = 0;
gdjs.warningCode.GDfloorObjects1.length = 0;
gdjs.warningCode.GDfloorObjects2.length = 0;
gdjs.warningCode.GDfloor2Objects1.length = 0;
gdjs.warningCode.GDfloor2Objects2.length = 0;
gdjs.warningCode.GDBlock2Objects1.length = 0;
gdjs.warningCode.GDBlock2Objects2.length = 0;
gdjs.warningCode.GDBlock3Objects1.length = 0;
gdjs.warningCode.GDBlock3Objects2.length = 0;
gdjs.warningCode.GDfakewallObjects1.length = 0;
gdjs.warningCode.GDfakewallObjects2.length = 0;
gdjs.warningCode.GDBlock3AltObjects1.length = 0;
gdjs.warningCode.GDBlock3AltObjects2.length = 0;
gdjs.warningCode.GDelevatorfloorObjects1.length = 0;
gdjs.warningCode.GDelevatorfloorObjects2.length = 0;
gdjs.warningCode.GDElevatorWallObjects1.length = 0;
gdjs.warningCode.GDElevatorWallObjects2.length = 0;
gdjs.warningCode.GDRedNetObjects1.length = 0;
gdjs.warningCode.GDRedNetObjects2.length = 0;
gdjs.warningCode.GDGreenNetObjects1.length = 0;
gdjs.warningCode.GDGreenNetObjects2.length = 0;
gdjs.warningCode.GDYellowNetObjects1.length = 0;
gdjs.warningCode.GDYellowNetObjects2.length = 0;
gdjs.warningCode.GDBlueNetObjects1.length = 0;
gdjs.warningCode.GDBlueNetObjects2.length = 0;
gdjs.warningCode.GDRedFloorObjects1.length = 0;
gdjs.warningCode.GDRedFloorObjects2.length = 0;
gdjs.warningCode.GDGreenFloorObjects1.length = 0;
gdjs.warningCode.GDGreenFloorObjects2.length = 0;
gdjs.warningCode.GDYellowFloorObjects1.length = 0;
gdjs.warningCode.GDYellowFloorObjects2.length = 0;
gdjs.warningCode.GDBlueFloorObjects1.length = 0;
gdjs.warningCode.GDBlueFloorObjects2.length = 0;
gdjs.warningCode.GDBallpitBallsObjects1.length = 0;
gdjs.warningCode.GDBallpitBallsObjects2.length = 0;
gdjs.warningCode.GDHandObjects1.length = 0;
gdjs.warningCode.GDHandObjects2.length = 0;
gdjs.warningCode.GDhandmarkerObjects1.length = 0;
gdjs.warningCode.GDhandmarkerObjects2.length = 0;
gdjs.warningCode.GDhandmarker2Objects1.length = 0;
gdjs.warningCode.GDhandmarker2Objects2.length = 0;
gdjs.warningCode.GDcursorObjects1.length = 0;
gdjs.warningCode.GDcursorObjects2.length = 0;
gdjs.warningCode.GDPaddedWallObjects1.length = 0;
gdjs.warningCode.GDPaddedWallObjects2.length = 0;
gdjs.warningCode.GDPaddedFloorObjects1.length = 0;
gdjs.warningCode.GDPaddedFloorObjects2.length = 0;
gdjs.warningCode.GDPaddedWallSMG4Objects1.length = 0;
gdjs.warningCode.GDPaddedWallSMG4Objects2.length = 0;
gdjs.warningCode.GDBlock4Objects1.length = 0;
gdjs.warningCode.GDBlock4Objects2.length = 0;
gdjs.warningCode.GDBlock1DetentionObjects1.length = 0;
gdjs.warningCode.GDBlock1DetentionObjects2.length = 0;
gdjs.warningCode.GDPosterObjects1.length = 0;
gdjs.warningCode.GDPosterObjects2.length = 0;
gdjs.warningCode.GDPoster2Objects1.length = 0;
gdjs.warningCode.GDPoster2Objects2.length = 0;
gdjs.warningCode.GDPoster3Objects1.length = 0;
gdjs.warningCode.GDPoster3Objects2.length = 0;


return;

}

gdjs['warningCode'] = gdjs.warningCode;
