gdjs.winCode = {};
gdjs.winCode.localVariables = [];
gdjs.winCode.idToCallbackMap = new Map();
gdjs.winCode.GDNewSpriteObjects1= [];
gdjs.winCode.GDNewSpriteObjects2= [];
gdjs.winCode.GDBlock1Objects1= [];
gdjs.winCode.GDBlock1Objects2= [];
gdjs.winCode.GDWoodObjects1= [];
gdjs.winCode.GDWoodObjects2= [];
gdjs.winCode.GDGrassGroundObjects1= [];
gdjs.winCode.GDGrassGroundObjects2= [];
gdjs.winCode.GDBlockInvObjects1= [];
gdjs.winCode.GDBlockInvObjects2= [];
gdjs.winCode.GDStairs1Objects1= [];
gdjs.winCode.GDStairs1Objects2= [];
gdjs.winCode.GDStairsInvObjects1= [];
gdjs.winCode.GDStairsInvObjects2= [];
gdjs.winCode.GDWoodStrsObjects1= [];
gdjs.winCode.GDWoodStrsObjects2= [];
gdjs.winCode.GDStopCrouchTrgObjects1= [];
gdjs.winCode.GDStopCrouchTrgObjects2= [];
gdjs.winCode.GDCameraObjects1= [];
gdjs.winCode.GDCameraObjects2= [];
gdjs.winCode.GDCamera2Objects1= [];
gdjs.winCode.GDCamera2Objects2= [];
gdjs.winCode.GDCameraColliderObjects1= [];
gdjs.winCode.GDCameraColliderObjects2= [];
gdjs.winCode.GDPaperObjects1= [];
gdjs.winCode.GDPaperObjects2= [];
gdjs.winCode.GDKeyObjects1= [];
gdjs.winCode.GDKeyObjects2= [];
gdjs.winCode.GDItemObjects1= [];
gdjs.winCode.GDItemObjects2= [];
gdjs.winCode.GDVendingMachine1Objects1= [];
gdjs.winCode.GDVendingMachine1Objects2= [];
gdjs.winCode.GDVendingMachine2Objects1= [];
gdjs.winCode.GDVendingMachine2Objects2= [];
gdjs.winCode.GDInteractTextObjects1= [];
gdjs.winCode.GDInteractTextObjects2= [];
gdjs.winCode.GDPaperUIObjects1= [];
gdjs.winCode.GDPaperUIObjects2= [];
gdjs.winCode.GDPaperTextObjects1= [];
gdjs.winCode.GDPaperTextObjects2= [];
gdjs.winCode.GDDoorObjects1= [];
gdjs.winCode.GDDoorObjects2= [];
gdjs.winCode.GDDoorWayPointObjects1= [];
gdjs.winCode.GDDoorWayPointObjects2= [];
gdjs.winCode.GDFadeBLACKObjects1= [];
gdjs.winCode.GDFadeBLACKObjects2= [];
gdjs.winCode.GDCrossObjects1= [];
gdjs.winCode.GDCrossObjects2= [];
gdjs.winCode.GDInfo_9595TextObjects1= [];
gdjs.winCode.GDInfo_9595TextObjects2= [];
gdjs.winCode.GDScary_9595PersonObjects1= [];
gdjs.winCode.GDScary_9595PersonObjects2= [];
gdjs.winCode.GDItemsUIObjects1= [];
gdjs.winCode.GDItemsUIObjects2= [];
gdjs.winCode.GDStaminaObjects1= [];
gdjs.winCode.GDStaminaObjects2= [];
gdjs.winCode.GDBaldiUIObjects1= [];
gdjs.winCode.GDBaldiUIObjects2= [];
gdjs.winCode.GDBaldiUIStaminaObjects1= [];
gdjs.winCode.GDBaldiUIStaminaObjects2= [];
gdjs.winCode.GDItemSlotObjects1= [];
gdjs.winCode.GDItemSlotObjects2= [];
gdjs.winCode.GDItemInventoryObjects1= [];
gdjs.winCode.GDItemInventoryObjects2= [];
gdjs.winCode.GDSodaSplashObjects1= [];
gdjs.winCode.GDSodaSplashObjects2= [];
gdjs.winCode.GDBearTrapObjects1= [];
gdjs.winCode.GDBearTrapObjects2= [];
gdjs.winCode.GDBlackBarsObjects1= [];
gdjs.winCode.GDBlackBarsObjects2= [];
gdjs.winCode.GDVendingMachine3Objects1= [];
gdjs.winCode.GDVendingMachine3Objects2= [];
gdjs.winCode.GDBaldiEnemyObjects1= [];
gdjs.winCode.GDBaldiEnemyObjects2= [];
gdjs.winCode.GDfloorObjects1= [];
gdjs.winCode.GDfloorObjects2= [];
gdjs.winCode.GDfloor2Objects1= [];
gdjs.winCode.GDfloor2Objects2= [];
gdjs.winCode.GDBlock2Objects1= [];
gdjs.winCode.GDBlock2Objects2= [];
gdjs.winCode.GDBlock3Objects1= [];
gdjs.winCode.GDBlock3Objects2= [];
gdjs.winCode.GDfakewallObjects1= [];
gdjs.winCode.GDfakewallObjects2= [];
gdjs.winCode.GDBlock3AltObjects1= [];
gdjs.winCode.GDBlock3AltObjects2= [];
gdjs.winCode.GDelevatorfloorObjects1= [];
gdjs.winCode.GDelevatorfloorObjects2= [];
gdjs.winCode.GDElevatorWallObjects1= [];
gdjs.winCode.GDElevatorWallObjects2= [];
gdjs.winCode.GDRedNetObjects1= [];
gdjs.winCode.GDRedNetObjects2= [];
gdjs.winCode.GDGreenNetObjects1= [];
gdjs.winCode.GDGreenNetObjects2= [];
gdjs.winCode.GDYellowNetObjects1= [];
gdjs.winCode.GDYellowNetObjects2= [];
gdjs.winCode.GDBlueNetObjects1= [];
gdjs.winCode.GDBlueNetObjects2= [];
gdjs.winCode.GDRedFloorObjects1= [];
gdjs.winCode.GDRedFloorObjects2= [];
gdjs.winCode.GDGreenFloorObjects1= [];
gdjs.winCode.GDGreenFloorObjects2= [];
gdjs.winCode.GDYellowFloorObjects1= [];
gdjs.winCode.GDYellowFloorObjects2= [];
gdjs.winCode.GDBlueFloorObjects1= [];
gdjs.winCode.GDBlueFloorObjects2= [];
gdjs.winCode.GDBallpitBallsObjects1= [];
gdjs.winCode.GDBallpitBallsObjects2= [];
gdjs.winCode.GDHandObjects1= [];
gdjs.winCode.GDHandObjects2= [];
gdjs.winCode.GDhandmarkerObjects1= [];
gdjs.winCode.GDhandmarkerObjects2= [];
gdjs.winCode.GDhandmarker2Objects1= [];
gdjs.winCode.GDhandmarker2Objects2= [];
gdjs.winCode.GDcursorObjects1= [];
gdjs.winCode.GDcursorObjects2= [];
gdjs.winCode.GDPaddedWallObjects1= [];
gdjs.winCode.GDPaddedWallObjects2= [];
gdjs.winCode.GDPaddedFloorObjects1= [];
gdjs.winCode.GDPaddedFloorObjects2= [];
gdjs.winCode.GDPaddedWallSMG4Objects1= [];
gdjs.winCode.GDPaddedWallSMG4Objects2= [];
gdjs.winCode.GDBlock4Objects1= [];
gdjs.winCode.GDBlock4Objects2= [];
gdjs.winCode.GDBlock1DetentionObjects1= [];
gdjs.winCode.GDBlock1DetentionObjects2= [];
gdjs.winCode.GDPosterObjects1= [];
gdjs.winCode.GDPosterObjects2= [];
gdjs.winCode.GDPoster2Objects1= [];
gdjs.winCode.GDPoster2Objects2= [];
gdjs.winCode.GDPoster3Objects1= [];
gdjs.winCode.GDPoster3Objects2= [];
gdjs.winCode.GDItemInventory2Objects1= [];
gdjs.winCode.GDItemInventory2Objects2= [];


gdjs.winCode.asyncCallback64610100 = function (runtimeScene, asyncObjectsList) {
asyncObjectsList.restoreLocalVariablesContainers(gdjs.winCode.localVariables);
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "titleNew", false);
}
gdjs.winCode.localVariables.length = 0;
}
gdjs.winCode.idToCallbackMap.set(64610100, gdjs.winCode.asyncCallback64610100);
gdjs.winCode.eventsList0 = function(runtimeScene) {

{


{
{
const asyncObjectsList = new gdjs.LongLivedObjectsList();
asyncObjectsList.backupLocalVariablesContainers(gdjs.winCode.localVariables);
runtimeScene.getAsyncTasksManager().addTask(gdjs.evtTools.runtimeScene.wait(5), (runtimeScene) => (gdjs.winCode.asyncCallback64610100(runtimeScene, asyncObjectsList)), 64610100, asyncObjectsList);
}
}

}


};gdjs.winCode.eventsList1 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.runtimeScene.sceneJustBegins(runtimeScene);
if (isConditionTrue_0) {
{gdjs.evtTools.sound.playSound(runtimeScene, "WIN.wav", false, 100, 1);
}

{ //Subevents
gdjs.winCode.eventsList0(runtimeScene);} //End of subevents
}

}


};

gdjs.winCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.winCode.GDNewSpriteObjects1.length = 0;
gdjs.winCode.GDNewSpriteObjects2.length = 0;
gdjs.winCode.GDBlock1Objects1.length = 0;
gdjs.winCode.GDBlock1Objects2.length = 0;
gdjs.winCode.GDWoodObjects1.length = 0;
gdjs.winCode.GDWoodObjects2.length = 0;
gdjs.winCode.GDGrassGroundObjects1.length = 0;
gdjs.winCode.GDGrassGroundObjects2.length = 0;
gdjs.winCode.GDBlockInvObjects1.length = 0;
gdjs.winCode.GDBlockInvObjects2.length = 0;
gdjs.winCode.GDStairs1Objects1.length = 0;
gdjs.winCode.GDStairs1Objects2.length = 0;
gdjs.winCode.GDStairsInvObjects1.length = 0;
gdjs.winCode.GDStairsInvObjects2.length = 0;
gdjs.winCode.GDWoodStrsObjects1.length = 0;
gdjs.winCode.GDWoodStrsObjects2.length = 0;
gdjs.winCode.GDStopCrouchTrgObjects1.length = 0;
gdjs.winCode.GDStopCrouchTrgObjects2.length = 0;
gdjs.winCode.GDCameraObjects1.length = 0;
gdjs.winCode.GDCameraObjects2.length = 0;
gdjs.winCode.GDCamera2Objects1.length = 0;
gdjs.winCode.GDCamera2Objects2.length = 0;
gdjs.winCode.GDCameraColliderObjects1.length = 0;
gdjs.winCode.GDCameraColliderObjects2.length = 0;
gdjs.winCode.GDPaperObjects1.length = 0;
gdjs.winCode.GDPaperObjects2.length = 0;
gdjs.winCode.GDKeyObjects1.length = 0;
gdjs.winCode.GDKeyObjects2.length = 0;
gdjs.winCode.GDItemObjects1.length = 0;
gdjs.winCode.GDItemObjects2.length = 0;
gdjs.winCode.GDVendingMachine1Objects1.length = 0;
gdjs.winCode.GDVendingMachine1Objects2.length = 0;
gdjs.winCode.GDVendingMachine2Objects1.length = 0;
gdjs.winCode.GDVendingMachine2Objects2.length = 0;
gdjs.winCode.GDInteractTextObjects1.length = 0;
gdjs.winCode.GDInteractTextObjects2.length = 0;
gdjs.winCode.GDPaperUIObjects1.length = 0;
gdjs.winCode.GDPaperUIObjects2.length = 0;
gdjs.winCode.GDPaperTextObjects1.length = 0;
gdjs.winCode.GDPaperTextObjects2.length = 0;
gdjs.winCode.GDDoorObjects1.length = 0;
gdjs.winCode.GDDoorObjects2.length = 0;
gdjs.winCode.GDDoorWayPointObjects1.length = 0;
gdjs.winCode.GDDoorWayPointObjects2.length = 0;
gdjs.winCode.GDFadeBLACKObjects1.length = 0;
gdjs.winCode.GDFadeBLACKObjects2.length = 0;
gdjs.winCode.GDCrossObjects1.length = 0;
gdjs.winCode.GDCrossObjects2.length = 0;
gdjs.winCode.GDInfo_9595TextObjects1.length = 0;
gdjs.winCode.GDInfo_9595TextObjects2.length = 0;
gdjs.winCode.GDScary_9595PersonObjects1.length = 0;
gdjs.winCode.GDScary_9595PersonObjects2.length = 0;
gdjs.winCode.GDItemsUIObjects1.length = 0;
gdjs.winCode.GDItemsUIObjects2.length = 0;
gdjs.winCode.GDStaminaObjects1.length = 0;
gdjs.winCode.GDStaminaObjects2.length = 0;
gdjs.winCode.GDBaldiUIObjects1.length = 0;
gdjs.winCode.GDBaldiUIObjects2.length = 0;
gdjs.winCode.GDBaldiUIStaminaObjects1.length = 0;
gdjs.winCode.GDBaldiUIStaminaObjects2.length = 0;
gdjs.winCode.GDItemSlotObjects1.length = 0;
gdjs.winCode.GDItemSlotObjects2.length = 0;
gdjs.winCode.GDItemInventoryObjects1.length = 0;
gdjs.winCode.GDItemInventoryObjects2.length = 0;
gdjs.winCode.GDSodaSplashObjects1.length = 0;
gdjs.winCode.GDSodaSplashObjects2.length = 0;
gdjs.winCode.GDBearTrapObjects1.length = 0;
gdjs.winCode.GDBearTrapObjects2.length = 0;
gdjs.winCode.GDBlackBarsObjects1.length = 0;
gdjs.winCode.GDBlackBarsObjects2.length = 0;
gdjs.winCode.GDVendingMachine3Objects1.length = 0;
gdjs.winCode.GDVendingMachine3Objects2.length = 0;
gdjs.winCode.GDBaldiEnemyObjects1.length = 0;
gdjs.winCode.GDBaldiEnemyObjects2.length = 0;
gdjs.winCode.GDfloorObjects1.length = 0;
gdjs.winCode.GDfloorObjects2.length = 0;
gdjs.winCode.GDfloor2Objects1.length = 0;
gdjs.winCode.GDfloor2Objects2.length = 0;
gdjs.winCode.GDBlock2Objects1.length = 0;
gdjs.winCode.GDBlock2Objects2.length = 0;
gdjs.winCode.GDBlock3Objects1.length = 0;
gdjs.winCode.GDBlock3Objects2.length = 0;
gdjs.winCode.GDfakewallObjects1.length = 0;
gdjs.winCode.GDfakewallObjects2.length = 0;
gdjs.winCode.GDBlock3AltObjects1.length = 0;
gdjs.winCode.GDBlock3AltObjects2.length = 0;
gdjs.winCode.GDelevatorfloorObjects1.length = 0;
gdjs.winCode.GDelevatorfloorObjects2.length = 0;
gdjs.winCode.GDElevatorWallObjects1.length = 0;
gdjs.winCode.GDElevatorWallObjects2.length = 0;
gdjs.winCode.GDRedNetObjects1.length = 0;
gdjs.winCode.GDRedNetObjects2.length = 0;
gdjs.winCode.GDGreenNetObjects1.length = 0;
gdjs.winCode.GDGreenNetObjects2.length = 0;
gdjs.winCode.GDYellowNetObjects1.length = 0;
gdjs.winCode.GDYellowNetObjects2.length = 0;
gdjs.winCode.GDBlueNetObjects1.length = 0;
gdjs.winCode.GDBlueNetObjects2.length = 0;
gdjs.winCode.GDRedFloorObjects1.length = 0;
gdjs.winCode.GDRedFloorObjects2.length = 0;
gdjs.winCode.GDGreenFloorObjects1.length = 0;
gdjs.winCode.GDGreenFloorObjects2.length = 0;
gdjs.winCode.GDYellowFloorObjects1.length = 0;
gdjs.winCode.GDYellowFloorObjects2.length = 0;
gdjs.winCode.GDBlueFloorObjects1.length = 0;
gdjs.winCode.GDBlueFloorObjects2.length = 0;
gdjs.winCode.GDBallpitBallsObjects1.length = 0;
gdjs.winCode.GDBallpitBallsObjects2.length = 0;
gdjs.winCode.GDHandObjects1.length = 0;
gdjs.winCode.GDHandObjects2.length = 0;
gdjs.winCode.GDhandmarkerObjects1.length = 0;
gdjs.winCode.GDhandmarkerObjects2.length = 0;
gdjs.winCode.GDhandmarker2Objects1.length = 0;
gdjs.winCode.GDhandmarker2Objects2.length = 0;
gdjs.winCode.GDcursorObjects1.length = 0;
gdjs.winCode.GDcursorObjects2.length = 0;
gdjs.winCode.GDPaddedWallObjects1.length = 0;
gdjs.winCode.GDPaddedWallObjects2.length = 0;
gdjs.winCode.GDPaddedFloorObjects1.length = 0;
gdjs.winCode.GDPaddedFloorObjects2.length = 0;
gdjs.winCode.GDPaddedWallSMG4Objects1.length = 0;
gdjs.winCode.GDPaddedWallSMG4Objects2.length = 0;
gdjs.winCode.GDBlock4Objects1.length = 0;
gdjs.winCode.GDBlock4Objects2.length = 0;
gdjs.winCode.GDBlock1DetentionObjects1.length = 0;
gdjs.winCode.GDBlock1DetentionObjects2.length = 0;
gdjs.winCode.GDPosterObjects1.length = 0;
gdjs.winCode.GDPosterObjects2.length = 0;
gdjs.winCode.GDPoster2Objects1.length = 0;
gdjs.winCode.GDPoster2Objects2.length = 0;
gdjs.winCode.GDPoster3Objects1.length = 0;
gdjs.winCode.GDPoster3Objects2.length = 0;
gdjs.winCode.GDItemInventory2Objects1.length = 0;
gdjs.winCode.GDItemInventory2Objects2.length = 0;

gdjs.winCode.eventsList1(runtimeScene);
gdjs.winCode.GDNewSpriteObjects1.length = 0;
gdjs.winCode.GDNewSpriteObjects2.length = 0;
gdjs.winCode.GDBlock1Objects1.length = 0;
gdjs.winCode.GDBlock1Objects2.length = 0;
gdjs.winCode.GDWoodObjects1.length = 0;
gdjs.winCode.GDWoodObjects2.length = 0;
gdjs.winCode.GDGrassGroundObjects1.length = 0;
gdjs.winCode.GDGrassGroundObjects2.length = 0;
gdjs.winCode.GDBlockInvObjects1.length = 0;
gdjs.winCode.GDBlockInvObjects2.length = 0;
gdjs.winCode.GDStairs1Objects1.length = 0;
gdjs.winCode.GDStairs1Objects2.length = 0;
gdjs.winCode.GDStairsInvObjects1.length = 0;
gdjs.winCode.GDStairsInvObjects2.length = 0;
gdjs.winCode.GDWoodStrsObjects1.length = 0;
gdjs.winCode.GDWoodStrsObjects2.length = 0;
gdjs.winCode.GDStopCrouchTrgObjects1.length = 0;
gdjs.winCode.GDStopCrouchTrgObjects2.length = 0;
gdjs.winCode.GDCameraObjects1.length = 0;
gdjs.winCode.GDCameraObjects2.length = 0;
gdjs.winCode.GDCamera2Objects1.length = 0;
gdjs.winCode.GDCamera2Objects2.length = 0;
gdjs.winCode.GDCameraColliderObjects1.length = 0;
gdjs.winCode.GDCameraColliderObjects2.length = 0;
gdjs.winCode.GDPaperObjects1.length = 0;
gdjs.winCode.GDPaperObjects2.length = 0;
gdjs.winCode.GDKeyObjects1.length = 0;
gdjs.winCode.GDKeyObjects2.length = 0;
gdjs.winCode.GDItemObjects1.length = 0;
gdjs.winCode.GDItemObjects2.length = 0;
gdjs.winCode.GDVendingMachine1Objects1.length = 0;
gdjs.winCode.GDVendingMachine1Objects2.length = 0;
gdjs.winCode.GDVendingMachine2Objects1.length = 0;
gdjs.winCode.GDVendingMachine2Objects2.length = 0;
gdjs.winCode.GDInteractTextObjects1.length = 0;
gdjs.winCode.GDInteractTextObjects2.length = 0;
gdjs.winCode.GDPaperUIObjects1.length = 0;
gdjs.winCode.GDPaperUIObjects2.length = 0;
gdjs.winCode.GDPaperTextObjects1.length = 0;
gdjs.winCode.GDPaperTextObjects2.length = 0;
gdjs.winCode.GDDoorObjects1.length = 0;
gdjs.winCode.GDDoorObjects2.length = 0;
gdjs.winCode.GDDoorWayPointObjects1.length = 0;
gdjs.winCode.GDDoorWayPointObjects2.length = 0;
gdjs.winCode.GDFadeBLACKObjects1.length = 0;
gdjs.winCode.GDFadeBLACKObjects2.length = 0;
gdjs.winCode.GDCrossObjects1.length = 0;
gdjs.winCode.GDCrossObjects2.length = 0;
gdjs.winCode.GDInfo_9595TextObjects1.length = 0;
gdjs.winCode.GDInfo_9595TextObjects2.length = 0;
gdjs.winCode.GDScary_9595PersonObjects1.length = 0;
gdjs.winCode.GDScary_9595PersonObjects2.length = 0;
gdjs.winCode.GDItemsUIObjects1.length = 0;
gdjs.winCode.GDItemsUIObjects2.length = 0;
gdjs.winCode.GDStaminaObjects1.length = 0;
gdjs.winCode.GDStaminaObjects2.length = 0;
gdjs.winCode.GDBaldiUIObjects1.length = 0;
gdjs.winCode.GDBaldiUIObjects2.length = 0;
gdjs.winCode.GDBaldiUIStaminaObjects1.length = 0;
gdjs.winCode.GDBaldiUIStaminaObjects2.length = 0;
gdjs.winCode.GDItemSlotObjects1.length = 0;
gdjs.winCode.GDItemSlotObjects2.length = 0;
gdjs.winCode.GDItemInventoryObjects1.length = 0;
gdjs.winCode.GDItemInventoryObjects2.length = 0;
gdjs.winCode.GDSodaSplashObjects1.length = 0;
gdjs.winCode.GDSodaSplashObjects2.length = 0;
gdjs.winCode.GDBearTrapObjects1.length = 0;
gdjs.winCode.GDBearTrapObjects2.length = 0;
gdjs.winCode.GDBlackBarsObjects1.length = 0;
gdjs.winCode.GDBlackBarsObjects2.length = 0;
gdjs.winCode.GDVendingMachine3Objects1.length = 0;
gdjs.winCode.GDVendingMachine3Objects2.length = 0;
gdjs.winCode.GDBaldiEnemyObjects1.length = 0;
gdjs.winCode.GDBaldiEnemyObjects2.length = 0;
gdjs.winCode.GDfloorObjects1.length = 0;
gdjs.winCode.GDfloorObjects2.length = 0;
gdjs.winCode.GDfloor2Objects1.length = 0;
gdjs.winCode.GDfloor2Objects2.length = 0;
gdjs.winCode.GDBlock2Objects1.length = 0;
gdjs.winCode.GDBlock2Objects2.length = 0;
gdjs.winCode.GDBlock3Objects1.length = 0;
gdjs.winCode.GDBlock3Objects2.length = 0;
gdjs.winCode.GDfakewallObjects1.length = 0;
gdjs.winCode.GDfakewallObjects2.length = 0;
gdjs.winCode.GDBlock3AltObjects1.length = 0;
gdjs.winCode.GDBlock3AltObjects2.length = 0;
gdjs.winCode.GDelevatorfloorObjects1.length = 0;
gdjs.winCode.GDelevatorfloorObjects2.length = 0;
gdjs.winCode.GDElevatorWallObjects1.length = 0;
gdjs.winCode.GDElevatorWallObjects2.length = 0;
gdjs.winCode.GDRedNetObjects1.length = 0;
gdjs.winCode.GDRedNetObjects2.length = 0;
gdjs.winCode.GDGreenNetObjects1.length = 0;
gdjs.winCode.GDGreenNetObjects2.length = 0;
gdjs.winCode.GDYellowNetObjects1.length = 0;
gdjs.winCode.GDYellowNetObjects2.length = 0;
gdjs.winCode.GDBlueNetObjects1.length = 0;
gdjs.winCode.GDBlueNetObjects2.length = 0;
gdjs.winCode.GDRedFloorObjects1.length = 0;
gdjs.winCode.GDRedFloorObjects2.length = 0;
gdjs.winCode.GDGreenFloorObjects1.length = 0;
gdjs.winCode.GDGreenFloorObjects2.length = 0;
gdjs.winCode.GDYellowFloorObjects1.length = 0;
gdjs.winCode.GDYellowFloorObjects2.length = 0;
gdjs.winCode.GDBlueFloorObjects1.length = 0;
gdjs.winCode.GDBlueFloorObjects2.length = 0;
gdjs.winCode.GDBallpitBallsObjects1.length = 0;
gdjs.winCode.GDBallpitBallsObjects2.length = 0;
gdjs.winCode.GDHandObjects1.length = 0;
gdjs.winCode.GDHandObjects2.length = 0;
gdjs.winCode.GDhandmarkerObjects1.length = 0;
gdjs.winCode.GDhandmarkerObjects2.length = 0;
gdjs.winCode.GDhandmarker2Objects1.length = 0;
gdjs.winCode.GDhandmarker2Objects2.length = 0;
gdjs.winCode.GDcursorObjects1.length = 0;
gdjs.winCode.GDcursorObjects2.length = 0;
gdjs.winCode.GDPaddedWallObjects1.length = 0;
gdjs.winCode.GDPaddedWallObjects2.length = 0;
gdjs.winCode.GDPaddedFloorObjects1.length = 0;
gdjs.winCode.GDPaddedFloorObjects2.length = 0;
gdjs.winCode.GDPaddedWallSMG4Objects1.length = 0;
gdjs.winCode.GDPaddedWallSMG4Objects2.length = 0;
gdjs.winCode.GDBlock4Objects1.length = 0;
gdjs.winCode.GDBlock4Objects2.length = 0;
gdjs.winCode.GDBlock1DetentionObjects1.length = 0;
gdjs.winCode.GDBlock1DetentionObjects2.length = 0;
gdjs.winCode.GDPosterObjects1.length = 0;
gdjs.winCode.GDPosterObjects2.length = 0;
gdjs.winCode.GDPoster2Objects1.length = 0;
gdjs.winCode.GDPoster2Objects2.length = 0;
gdjs.winCode.GDPoster3Objects1.length = 0;
gdjs.winCode.GDPoster3Objects2.length = 0;
gdjs.winCode.GDItemInventory2Objects1.length = 0;
gdjs.winCode.GDItemInventory2Objects2.length = 0;


return;

}

gdjs['winCode'] = gdjs.winCode;
